### ISSUE TITLE
Crash when reloading languages with Language Reload

### ISSUE THREAD

**Issue by Felix14-v2** [AlurienFlame/Chatsounds#10]
**Description**
When you try to reload or cycle languages in the main menu using (Shift+)F3+J with Language Reload installed, Minecraft crashes.

**To reproduce**
- Install ChatSounds
- Install Language Reload
- Launch Minecraft
- Press F3+J or Shift+F3+J
- See the crash

**Info**
- Minecraft 1.19.2 (can confirm in previous versions)
- Fabric 0.14.9
- Fabric API 0.61.0
- ChatSounds 1.1.6
- Language Reload 1.3.2

**Additional**
[latest.log](https://github.com/AlurienFlame/Chatsounds/files/9595241/latest.log)
[#14](https://github.com/Jerozgen/LanguageReload/issues/14)
```
[00:02:44] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_746.method_23317()" because "client.field_1724" is null
```

**Comment by AlurienFlame** [comment]
Looks like `class_746.method_23317 `is the `SendChatMessage` method I'm mixing in. Not sure why language reload would set something to null there. Looks like the only things following a `client.` are `player` and `getSoundManager()`, so maybe language reload is breaking one of those things? And I'm pretty sure `getSoundManager()` is a method, not a field, so `client.field_1724` is probably `client.player`. No idea why that would become null, that seems like it should break more things than just my mod. I might be totally wrong though, no time to get in there and debug for a long while.
