### ISSUE TITLE
Wrong version on Curseforge

### ISSUE THREAD

**Issue by Chiloven945** [AlurienFlame/Chatsounds#14]
The mod version 1.1.8 doesn't support the game version 1.19 to 1.19.3, because the depends given in the file are not available in game versions 1.19 to 1.19.3.
![image](https://github.com/AlurienFlame/Chatsounds/assets/116699482/af0163a6-3839-44aa-ab47-e5db15fb5fb0)
![image](https://github.com/AlurienFlame/Chatsounds/assets/116699482/87c4fcc3-2a84-4861-9783-8ef1de01e96b)
![image](https://github.com/AlurienFlame/Chatsounds/assets/116699482/704d0d14-599a-4fed-b3f3-a1ec634a3fc8)

**Comment by AlurienFlame** [comment]
This should be resolved now, thanks for bringing it to my attention. The mistake was a by-product of my updating workflow, and one I'll aim to keep in mind for future updates.
