### ISSUE TITLE
Crashes in 1.19.1.

### ISSUE THREAD

**Issue by Cookie-Kurokami** [AlurienFlame/Chatsounds#6]
Attempting to run this mod in the latest version of MC causes the game to crash on startup with this error.
[crash-2022-07-29_21.51.41-client.txt](https://github.com/AlurienFlame/Chatsounds/files/9224198/crash-2022-07-29_21.51.41-client.txt)

**Comment by AlurienFlame** [comment]
Thanks for bringing this to my attention. Try release [1.1.5](https://github.com/AlurienFlame/Chatsounds/releases/tag/1.1.5%2B1.19.1), it should resolve this problem.
