### ISSUE TITLE
No 1.19+ Sounds

### ISSUE THREAD

**Issue by LOLboy199** [AlurienFlame/Chatsounds#8]
Looks like many of the newer sounds cannot be used such as Goat Horns, Warden Sounds, frogs etc. I didn't check all of them, but it also seems like some older sounds don't exist, like anything for goats- and those were added in 1.17. Those sounds simply cannot be found or entered into the Sound id slot.

**Comment by AlurienFlame** [comment]
I've updated the hardcoded list of supported sounds to include stuff added since 1.16, but goat horns are still broken because Minecraft implements them weirdly. At some point I'll rework the config to dynamically support new updates and modded sounds, but this will have to do for now.
