### ISSUE TITLE
Wrong compatibility tags

### ISSUE THREAD

**Issue by Navota** [AlurienFlame/Chatsounds#9]
1.1.5 and 1.1.6 are marked as compatible with 1.19 on curseforge and modrinth. Both versions want builds of fabric api and mod menu that are 1.19.1+
1.1.4 still shows up as 1.1.3 and has the 1.19.1-rc3 of fapi 0.58.3 mentioned as a dependency. It should just be 0.58.0, you wouldnt be able to run other mods with that fapi version on 1.19.

**Comment by AlurienFlame** [comment]
Thanks for letting me know. I only actively support the latest versions of my mods and of Minecraft, so issues with older releases are going to go unfixed, but I'll try to be more aware of versioning paradoxes like these in the future. (Won't fix)
